Repository m3ntorship/m3ntorship.com-v2, pull requests merged in 2022-08, with the labels that each got.

#59 feat: added applicationPage initial screen
  package.json
  public/images/applications-page/arrow-left.svg
  public/images/applications-page/arrow-right.svg
  public/images/applications-page/arrow.svg
  public/images/applications-page/logo.svg
  public/images/applications-page/mentee.svg
  public/images/applications-page/mentor.svg
  public/images/applications-page/submit.svg
  src/modules/ApplicationsPage/components/ApplicationsHeader/index.tsx
  src/modules/ApplicationsPage/components/ApplicationsTab/index.tsx
  src/modules/ApplicationsPage/components/MenteeApplication/index.tsx
  src/modules/ApplicationsPage/components/MentorApplication/index.tsx
  src/modules/ApplicationsPage/index.tsx
  src/pages/applications/index.tsx
  utils/tailwind/figmaTokens.json
Labels: ready for review

#61 I56 application form content step one mentee
  src/modules/ApplicationsPage/components/molecules/ApplicationsHeader/index.tsx
  src/modules/ApplicationsPage/components/molecules/ApplicationsTab/index.tsx
  src/modules/ApplicationsPage/components/molecules/MenteeApplicationStepOne/index.tsx
  src/modules/ApplicationsPage/components/molecules/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/MentorApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/index.tsx
  src/modules/ApplicationsPage/index.tsx
Labels: ready for review

#62 I57 application form content step two mentee
  src/modules/ApplicationsPage/components/molecules/ApplicaitonsTab/index.tsx
  src/modules/ApplicationsPage/components/molecules/MenteeApplicationStepTwo/index.tsx
  src/modules/ApplicationsPage/components/molecules/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
Labels: ready for review

#65 feat: added mentorApplication
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/MentorApplication/index.tsx
Labels: ready for review

#64 I58 application form content step three mentee
  src/modules/ApplicationsPage/components/molecules/MenteeApplicationStepThree/index.tsx
  src/modules/ApplicationsPage/components/molecules/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
Labels: ready for review

#68 application steps form control and state
  package.json
  src/modules/ApplicationsPage/components/molecules/MenteeApplicationStepOne/index.tsx
  src/modules/ApplicationsPage/components/molecules/MenteeApplicationStepThree/index.tsx
  src/modules/ApplicationsPage/components/molecules/MenteeApplicationStepTwo/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/utils.ts
  src/modules/ApplicationsPage/components/organisms/MentorApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/MentorApplication/utils.ts
  src/shared/constants/index.ts
  yarn.lock
Labels: ready for review, feature

#69 wrap the application page with layout component
  src/modules/ApplicationsPage/components/molecules/ApplicationsHeader/index.tsx
  src/modules/ApplicationsPage/index.tsx
  src/modules/HomePage/components/organisms/AvailableProgramsSection/AvailableProgramCard/index.tsx
  src/modules/HomePage/components/organisms/EnrollSection/index.tsx
  src/modules/HomePage/components/organisms/HeroSection/Navbar.tsx
  src/modules/HomePage/components/organisms/HeroSection/index.tsx
  src/pages/applications/index.tsx
  src/pages/index.tsx
  src/shared/hocs/DefaultLayout/index.tsx
Labels: ready for review, feature

#72 fix responsive issues in applications page
  src/modules/ApplicationsPage/components/molecules/ApplicaitonsTab/index.tsx
  src/modules/ApplicationsPage/components/molecules/ApplicationsTab/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/MentorApplication/index.tsx
  src/modules/ApplicationsPage/index.tsx
  src/pages/applications/index.tsx
  src/shared/constants/index.ts
  src/shared/hocs/DefaultLayout/index.tsx
Labels: bug, ready for review

#71 feat: created ApplicationSent screen
  public/images/applications-page/home.svg
  public/images/applications-page/success.png
  src/modules/ApplicationsPage/components/molecules/ApplicationSuccess/index.tsx
  src/modules/ApplicationsPage/components/organisms/MenteeApplication/index.tsx
  src/modules/ApplicationsPage/components/organisms/MentorApplication/index.tsx
  src/modules/ApplicationsPage/index.tsx
Labels: ready for review, feature
