Repository m3ntorship/m3ntorship.com-v2, pull requests merged in 2022-10, with the labels that each got.

#85 feat: created HeroSection component
  public/images/testimonials-page/mentees.png
  src/modules/TestimonialsPage/components/organisms/TestimonialsHero/TestimonialsHero.module.css
  src/modules/TestimonialsPage/components/organisms/TestimonialsHero/index.tsx
  src/modules/TestimonialsPage/components/organisms/index.ts
  src/modules/TestimonialsPage/index.tsx
  src/pages/testimonials/index.tsx
  tailwind.config.js
Labels: ready for review, feature

#94 feat: created TestimonialCard component
  package.json
  public/images/testimonials-page/icons/github.svg
  public/images/testimonials-page/icons/linkedin-square.svg
  src/modules/TestimonialsPage/components/molecules/TestimonialCard/index.tsx
  src/modules/TestimonialsPage/components/molecules/index.ts
  yarn.lock
Labels: ready for review, feature

#98 test: add test scenarios for testimonial card
  src/modules/TestimonialsPage/components/molecules/TestimonialCard/TestimonialCard.test.tsx
Labels: ready for review

#96 feat: create FeedbackSection component
  package.json
  src/modules/TestimonialsPage/api/getFeedbacks/index.ts
  src/modules/TestimonialsPage/api/index.ts
  src/modules/TestimonialsPage/components/molecules/TestimonialCard/index.tsx
  src/modules/TestimonialsPage/components/organisms/FeedbackSection/FeedbackSection.test.tsx
  src/modules/TestimonialsPage/components/organisms/FeedbackSection/index.tsx
  src/modules/TestimonialsPage/components/organisms/index.ts
  src/modules/TestimonialsPage/components/types/IFeedback.d.ts
  src/modules/TestimonialsPage/index.tsx
  src/pages/testimonials/index.tsx
  yarn.lock
Labels: ready for review, feature

#101 feat: created Motivation section
  src/modules/StoryPage/components/organisms/Motivations/Motivation.module.css
  src/modules/StoryPage/components/organisms/Motivations/index.tsx
  src/modules/StoryPage/components/organisms/index.tsx
  src/modules/StoryPage/index.tsx
  tailwind.config.js
Labels: ready for review, feature

#100 99 storybook
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/shared/components/molecules/Footer/Footer.stories.tsx
  yarn.lock
Labels: ready for review

#102 feat: created ContactSection component
  public/images/contact-page/icons/facebook.svg
  public/images/contact-page/icons/github.svg
  public/images/contact-page/icons/instagram.svg
  public/images/contact-page/icons/linkedin.svg
  public/images/contact-page/icons/twitter.svg
  src/modules/ContactPage/components/molecules/ContactLinks/index.tsx
  src/modules/ContactPage/components/molecules/index.ts
  src/modules/ContactPage/components/organisms/ContactSection/index.tsx
  src/modules/ContactPage/components/organisms/index.ts
  src/modules/ContactPage/index.tsx
  tailwind.config.js
Labels: ready for review, feature

#106 feat: navbar active links
  src/pages/mentors/index.tsx
  src/pages/programs/index.tsx
  src/shared/components/molecules/Navbar/index.tsx
  src/shared/components/molecules/Navbar/links.ts
Labels: ready for review

#105 91 contact us contact us form 1
  package.json
  src/modules/ApplicationsPage/components/molecules/ApplicationSuccess/index.tsx
  src/modules/ApplicationsPage/index.tsx
  src/modules/ContactPage/components/molecules/ContactUsForm/ContactUsForm.test.tsx
  src/modules/ContactPage/components/molecules/ContactUsForm/index.tsx
  src/modules/ContactPage/components/molecules/index.ts
  src/modules/ContactPage/components/molecules/index.tsx
  src/modules/ContactPage/index.tsx
  src/shared/components/molecules/ApplicationSuccess/index.tsx
  src/shared/components/molecules/index.ts
  yarn.lock
Labels: feature

#104 feat: add Envision section in story page
  public/images/story-page/pillar-1.png
  public/images/story-page/pillar-2.png
  public/images/story-page/pillar-3.png
  public/images/story-page/pillar-4.png
  public/images/story-page/vision.png
  src/modules/StoryPage/components/organisms/Envision/index.tsx
  src/modules/StoryPage/components/organisms/index.tsx
  src/modules/StoryPage/index.tsx
  tailwind.config.js
Labels: ready for review, feature
